#server.port=9595
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.open-in-view=false


security.oauth2.resource.filter-order=3

#https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
#${SIGNING_KEY}
security.signing-key=MaYzkSjmkzPC57L
security.encoding-strength=256
security.security-realm=Spring Boot JWT

security.jwt.client-id=${SECURITY_JWT_CLIENT_ID}
security.jwt.client-secret=${CLIENT_SECRET}
security.jwt.grant-type=password
security.jwt.scope-read=${SECURITY_JWT_SCOPE_READ}
security.jwt.scope-write=${SECURITY_JWT_SCOPE_WRITE}
security.jwt.resource-ids=${SECURITY_JWT_RESOURCE_IDS}