apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: mediapp17
  POSTGRES_USER: postgres
  # Configuración no sensible del backend jwt
  CLIENT_ID: mitomediapp
  SCOPE_READ: read
  SCOPE_WRITE: write
  RESOURCE_IDS: mitoresourceid